spring:
  application:
    name: kr-server
  profiles:
    active: ${APP_PROFILE}
  servlet:
    multipart:
      resolve-lazily: false
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  gemini:
    api-key: ${GEMINI_APIKEY}
    base-url: https://generativelanguage.googleapis.com/v1beta
  api:
    security:
      token:
        secret: minha-chave-segura-123
        expiration-minutes: 120

server:
  servlet:
    context-path: /kero-server/v1

---
spring:
  config:
    activate:
      on-profile: development

modules:
  base-url: "http://localhost:8080/kero-server/v1"

---
spring:
  config:
    activate:
      on-profile: prod

modules:
  base-url: "https://kero-server.com/kero-server/v1"

logging:
  structured:
    format:
      console: ecs

---
spring:
  config:
    activate:
      on-profile: test

modules:
  base-url: "http://localhost:8080/kero-server/v1"

logging:
  structured:
    format:
      console: ecs
